/*
 * This file was automatically generated by EvoSuite
 * Sat May 30 09:45:08 GMT 2020
 */

package com.github.hofls.javatests.evosuite.math;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.fail;

public class Mathematics_ESTest  {

  @Test
  public void test0()  throws Throwable  {
      int int0 = Mathematics.sum(2667, 1000);
      assertEquals(3667, int0);
  }

  @Test
  public void test1()  throws Throwable  {
      int int0 = Mathematics.sum(1000, (-30));
      assertEquals(970, int0);
  }

  @Test
  public void test2()  throws Throwable  {
      int int0 = Mathematics.sum((-30), (-30));
      assertEquals((-60), int0);
  }

  @Test
  public void test3()  throws Throwable  {
      int int0 = Mathematics.sum(0, 0);
      assertEquals(0, int0);
  }

  @Test
  public void test4()  throws Throwable  {
      int int0 = Mathematics.sum(1030, 760);
      assertEquals(1790, int0);
  }

  @Test
  public void test5()  throws Throwable  {
      int int0 = Mathematics.sum((-1623), (-1623));
      assertEquals((-3333), int0);
  }

  @Test
  public void test6()  throws Throwable  {
      int int0 = Mathematics.sum(1030, 1030);
      assertEquals(7777, int0);
  }

  @Test
  public void test7()  throws Throwable  {
      Mathematics mathematics0 = new Mathematics();
  }

  @Test
  public void test8()  throws Throwable  {
      // Undeclared exception!
      try { 
        Mathematics.divideByNull();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Quit trying to destroy the universe please
         //
      }
  }
}
